const POINTS_ADDING_PROCESS = "POINTS_ADDING_PROCESS";
const POINTS_ADDING_POSITIVE = "POINTS_ADDING_POSITIVE";
const POINTS_ADDING_NEGATIVE = "POINTS_ADDING_NEGATIVE";

const POINTS_DELETING_PROCESS = "POINTS_DELETING_PROCESS";
const POINTS_DELETING_POSITIVE = "POINTS_DELETING_POSITIVE";
const POINTS_DELETING_NEGATIVE = "POINTS_DELETING_NEGATIVE";

const POINTS_UPDATING_PROCESS = "POINTS_UPDATING_PROCESS";

const POINTS_GETALL = "POINTS_GETALL";
const POINTS_GET = "POINTS_GET";
const POINT_RESTORE = "POINTS_RESTORE";

export default {
  POINTS_ADDING_PROCESS,
  POINTS_ADDING_POSITIVE,
  POINTS_ADDING_NEGATIVE,

  POINTS_DELETING_PROCESS,
  POINTS_DELETING_POSITIVE,
  POINTS_DELETING_NEGATIVE,

  POINTS_UPDATING_PROCESS,

  POINTS_GET,
  POINTS_GETALL,
  POINT_RESTORE
};
